services:
  base:
    build:
      context: devcontainer/debian/.
      args:
        USERNAME: test-dev
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      DISPLAY: ":0"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/ranta/.ssh:/home/test-dev/.ssh
      - /home/ranta/github:/home/test-dev/work
      - /home/ranta/media:/home/test-dev/media
      # - /home/ranta/.kube:/home/test-dev/.kube
      # - /home/ranta/.aws:/home/test-dev/.aws
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000-3010:3000-3010"
